# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.13528506, 0.28920228, 0.75968255],
       [0.73430612, 0.19485741, 0.79750335],
       [0.96577264, 0.31718344, 0.58039931],
       [0.00105232, 0.43349364, 0.09719328],
       [0.58797164, 0.37564832, 0.43733369],
       [0.98900215, 0.01658961, 0.22364077],
       [0.06694911, 0.936969  , 0.0321423 ],
       [0.47187247, 0.95518878, 0.45689849],
       [0.8565025 , 0.93432654, 0.31352653],
       [0.9481358 , 0.63352934, 0.08876693],
       [0.65658172, 0.30687232, 0.90717128],
       [0.56575779, 0.04864868, 0.34382689],
       [0.82989784, 0.2760495 , 0.1235917 ],
       [0.06944816, 0.46890288, 0.07287815],
       [0.08471417, 0.08227496, 0.91701094],
       [0.47040069, 0.5117469 , 0.3061983 ],
       [0.31855896, 0.87615865, 0.46458283],
       [0.43035196, 0.10957722, 0.07102633],
       [0.42450688, 0.4186096 , 0.75450214],
       [0.90770458, 0.1378851 , 0.67595409],
       [0.7740047 , 0.94628551, 0.18722343],
       [0.90052101, 0.28691423, 0.12731034],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.90770458, 0.1378851 , 0.67595409],
       [0.8565025 , 0.93432654, 0.31352653]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 0]),
 array([0.79154232, 0.21928769, 0.21130667, 1.01460765, 0.46443535,
        0.4752991 , 0.83819964, 0.41101218, 0.        , 0.38651326,
        0.38089468, 0.48497342, 0.57467164, 0.945508  , 0.85936843,
        0.57245251, 0.56176931, 0.77110599, 0.56431911, 0.        ,
        0.15133201, 0.56856947, 0.78088612, 0.58147202, 0.54526748,
        0.34874146, 0.89128194, 0.4191776 , 0.3447816 , 0.9694602 ]))

In [6]:
labels = clusters[0]
labels

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0])

In [7]:
#The plotly.plotly module is deprecated,
#please install the chart-studio package and use the
#chart_studio.plotly module instead. 
#import plotly.plotly as py
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

In [8]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
#ply.plot(fig, filename='Clusters')
ply.plot(fig, filename='Clusters.html')


'Clusters.html'

In [9]:
from scipy.cluster.vq import kmeans

In [10]:
kmeans(data, clust_centers)

(array([[0.59144307, 0.22242447, 0.57646594],
        [0.3930144 , 0.77946664, 0.24292622]]),
 0.41830251487310066)

In [11]:
kmeans(data, 2)

(array([[0.59144307, 0.22242447, 0.57646594],
        [0.3930144 , 0.77946664, 0.24292622]]),
 0.41830251487310066)